CHANGELOG.md
README.md
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateTerminalCommand.kt

- Using `nx` command instead of `ng` for executing terminal commands
- Wrapping flag values that contain spaces inside single quotes when executing commands
- Cleanup the readme and changelog
CLOSES #1 
CLOSES #3

few fixes regarding executing terminal commands

---

CHANGELOG.md
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/SchematicSelectionTabListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/RunTerminalWindow.kt

- When trying to run (or dry run) a schematic, but you didn't fill out all required fields, the warning comes up, but it still runs the commands when closing warning message.
- Going between `Dry Run` and `Run` commands does not switch tabs even though commands are run in the background.
- If warning comes up about required fields not filled out, it should not run the commands.
- Switching between `Dry Run` and `Run` commands should also switch to the corresponding tabs.
CLOSES #7

fix: tab switching on DryRun/Run and required fields flow fix

---

src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateTerminalCommand.kt

User needs to have Nx installed globally.
The locally installed version of Nx should be used.
- user might not have Nx installed globally
- global version might be different to project required version
#2

feat: use Nx CLI from node_modules

---

CHANGELOG.md
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/RunTerminalWindow.kt

- When trying to run (or dry run) schematic, if user clicks on same button twice while terminal is still executing first command, then next action queues.
- If shell instance is still running a command, then if user clicks on the same button again, nothing happens.
- User would have to click the button (Dry Run or Run) again after the original command has finished executing.
No more double clicking funny business.
CLOSES #6

fix: double clicking on buttons to run commands

---

CHANGELOG.md
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/ReFetchSchematicsListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/GenerateToolWindow.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/SchematicsListToolTab.kt

- There is no way to refresh list of available schematics (in scenario where you generate new schematic)
- There should be a `Refresh` button next to the search bar on list of schematics.
- Upon clicking on the button, it should refresh the panel that shows the list of available schematics.
- So we don't need to reopen webstorm everytime we create a new schematic 😆 
CLOSES #13

feat: adding refresh listener for list of schematics

---

gradle.properties

Plugin version is at `0.2.0`
Update version of plugin to `0.2.1`
Prepare for release

chore: prepare-release of 0.2.1

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/com/github/etkachev/nxwebstorm/actions/NxActionGroup.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/GenerateToolWindow.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/ExternalSchematicsSettingsComponent.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/ExternalSchematicsSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/NewExternalSchematicDialog.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsComponent.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/ArrayUtils.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GetNxData.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/PackageJsonHelper.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/PsiUtils.kt
src/main/resources/META-INF/plugin.xml

* We did not have any plugin settings
We now have plugin settings with following configurables:
* Toggle whether to scan only explicit external libraries for schematics (faster) or do full scan of node_modules (slower)
* Specify external libraries to scan (if above is toggled on)
* configure location of custom schematics (by default its `/tools/schematics`)
Start of being able to configure the plugin
CLOSES #18

feat: plugin settings

---

CHANGELOG.md
gradle.properties

version is at 0.2.1
Increase to next minor version 0.3.0
Preparing next release

chore: increasing minor version of plugin for release

---

src/main/kotlin/com/github/etkachev/nxwebstorm/ui/GenerateToolWindow.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/ExternalSchematicsSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsComponent.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt
src/main/kotlin/icons/PluginIcons.java
src/main/kotlin/icons/PluginIcons.kt
src/main/resources/META-INF/plugin.xml

* Settings for plugin are currently set as application level (global settings)
* No icon rendered for Nx tool tab
* Move settings for plugin to be project level
* New icon rendering for Nx tool tab.
* Made more sense to have settings flexible per project.

feat: nrwl icon and settings migration

---

CHANGELOG.md
gradle.properties

* Changelog is outdated.
* plugin version is 0.3.0
* Updated changelog to include latest
* update plugin version to 0.4.0
Prepare release

chore: upping version and updating changelog

---

CHANGELOG.md
build.gradle.kts
gradle.properties

- `pluginUntilBuild` was set to 202.*
- `pluginUntilBuild` should be set to latest 203.*
New version of Webstorm came out

chore: updated pluginUntilBuild to latest 203 with latest webstorm update

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/services/MyProjectService.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/ExternalSchematicsSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt

- default directory for custom schematics are set to `/tools/schematics`
- With Nx 11, default is now `/tools/generators`.
- Depending on nx version (>= 11) set default directory for custom schematics
- updated nx version

feat: updated defaults for custom schematics dir depending on nx cli version

---

.github/dependabot.yml
.run/Run IDE with Plugin.run.xml
.run/Run Plugin Tests.run.xml
.run/Run Plugin Verification.run.xml
CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/MyBundle.kt

- plugin is off of plugin template [0.7.1](https://github.com/JetBrains/intellij-platform-plugin-template/releases/tag/v0.7.1)
- plugin should be off of plugin template [0.8.0](https://github.com/JetBrains/intellij-platform-plugin-template/releases/tag/v0.8.0)
- use latest plugin template

chore: update to latest plugin template 0.8.0

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/ReFetchSchematicsListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/SchematicsListToolTab.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/buttons/SchematicActionButtons.kt

- Refresh button for schematics list was text button
- platformVersion on gradle.properties was set to `2020.2`
- this caused kotlin errors in IDE with latest update to Intellij
- Refresh button for schematics list should be icon button
- platformVersion on gradle.properties should be set to `2020.3`
- simpler ui for refresh button
- fix IDE errors related to kotlin

feat: refresh button icon

---

CHANGELOG.md
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt

- when going to configure plugin settings:
- custom schematics folder was not able to change or be configured
- when configuring plugin settings:
- custom schematics folder is now fully configurable and has a default fallback when empty.
- bug fixes

fix: bug in settings for custom schematics directory

---

CHANGELOG.md
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/SchematicSelectionTabListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateTerminalCommand.kt

- if any args from the schematics contain [bash shortcuts](https://kapeli.com/cheat_sheets/Bash_Shortcuts.docset/Contents/Resources/Documents/index) that start with `!` then it sometimes replaces that string with some recent ran commands within bash.
- any args inputted for schematics that contain character `!` should be wrapped in single quote strings to avoid bash shortcuts executing.
- also new util for outputting commands in list of strings rather than single string.
- small edge case bug fix.

fix: bash commands sometimes execute within commands of schematics

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsState.kt

- under settings for plugin, default list of schematic packages to scan were missing a few new ones.
- under settings for plugin, default list of schematic packages to scan now include: 
- `@nrwl/react`
- `@nrwl/web`
- `@nrwl/gatsby`
- `@nrwl/bazel`
- `@nrwl/express`
- `@nrwl/next`
- `@nrwl/nx-plugin`
More default setup for external schematics to scan.
#43

feat: added more nrwl default packages for settings

---

CHANGELOG.md
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/DryRunAction.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/actions/Generate.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/services/MyProjectService.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/services/NodeDebugConfigState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/RunTerminalWindow.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsComponent.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateTerminalCommand.kt

- there is assumption that every workspace opened in Jetbrains IDE is the root nx project.
- debugging does not work when running in a workspace that does not have any run configs setup
- add project settings to nx-webstorm plugin so that you can configure where the root directory is for nx project.
- by default it is `/`
- fix bug so that workspaces that don't have run configs setup, will have `RunManager` setup before adding nx debug config
- bug fixes and more configuration with unique workspaces using nx
#42

feat(settings): configure root nx directory

---

CHANGELOG.md
gradle.properties

- support for `pluginUntilBuild=203.*`
- support for `pluginUntilBuild=211.*`
smooth transition when 2021 version comes out.

chore: support for upcoming 2021 IDE versions

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt

- There are sometimes cases where directory split fails as mentioned on #54 .
- Plugin should not crash 
- Attempting to fix edge case on indexing issue.
#54

fix: fixing possible index issue when searching schematics

---

CHANGELOG.md
gradle.properties

- current `pluginUntilBuild` is set to `211.*`
- update `pluginUntilBuild` to latest `212.*`
prepare for upcoming webstorm version update

upgrade to latest webstorm version

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/models/FullSchematicInfo.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt

- when searching nx custom schematics/generators, plugin searches schema.jsons via the `id` property.
- when searching nx custom schematics/generators, plugin should search schema.json files first by `id` property, then `$id` if former was not found.
- better support on different schema json files.
#71

feat: support for id prop for new schema
