CHANGELOG.md
gradle.properties

incrementing plugin version

---

CHANGELOG.md
gradle.properties

- Increasing the minor version, preparing for release
- Updating changelog to have latest info

chore: incrementing minor version and updating changelog. preparing release

---

detekt-config.yml
src/main/kotlin/com/github/etkachev/nxwebstorm/models/FormComboStringParams.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/RunSchematicPanel.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/formcontrols/AutoCompleteFocusListenerPopup.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/formcontrols/AutoCompleteKeyUpDownListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/formcontrols/BasicAutoCompleteField.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/formcontrols/BasicAutoCompleteProvider.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/formcontrols/StringListTable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FormControl.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateFormControl.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GetNxData.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/RowFilter.kt

* We do not have an auto-complete form control
* Schematics do not show a list of projects in autocomplete
* New autocomplete form control
* Be able to pull in all projects within repo to populate into schematic ui.
Get closer to how VsCode NxConsole has autocomplete for project list in schematic ui
CLOSES #22

feat: autocomplete for projects list

---

CHANGELOG.md
README.md
gradle.properties

- Outdated readme
- Updated readme to include latest features.

doc: updated readme

---

CHANGELOG.md
README.md
gradle.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/DryRunAction.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/SchematicActionListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/SchematicSelectionTabListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/actions/Generate.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/models/CliCommands.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/models/FullSchematicInfo.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/models/SchematicInfo.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/services/MyProjectService.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/services/NodeDebugConfigState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/GenerateTable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/RunSchematicDialog.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateTerminalCommand.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GetSchematicList.kt

- It is not possible to run or debug custom schematics for non-nx angular projects.
- Added support to be able to run or debug custom schematics for non-nx angular projects.
Broader support for people with custom schematics.

feat: support for custom schematics in non-nx angular projects.

---

.editorconfig
.github/workflows/build.yml
.github/workflows/release.yml
.run/Run IDE with Plugin.run.xml
.run/Run Plugin Tests.run.xml
.run/Run Plugin Verification.run.xml
CHANGELOG.md
README.md
build.gradle.kts
detekt-config.yml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
src/main/kotlin/com/github/etkachev/nxwebstorm/listeners/MyProjectManagerListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/services/NodeDebugConfigState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/RunSchematicPanel.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/SchematicsListToolTab.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/ArrayUtils.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateFormControl.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GetSchematicList.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/RowFilter.kt
src/main/resources/META-INF/plugin.xml

- Plugin is based on plugin template 0.3.0
- Update plugin to latest template version 0.7.0
Have latest updates and fixes for jetbrains plugin template.

chore: updating to latest plugin template 0.7.0

---

CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Plugin template used is 0.7.0
Plugin template used should be 0.7.1
latest plugin template version

updated to latest plugin template updates

---

.github/workflows/build.yml
CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- using jetbrains plugin 0.8.0
- update to latest jetbrains plugin 0.8.1
- getting latest

chore: updated to latest plugin template

---

CHANGELOG.md
gradle.properties

chore: up version and cleanup changelog

---

CHANGELOG.md
LICENSE
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/main/resources/META-INF/plugin.xml

- plugin based on jetbrains template 0.8.1
- plugin based on jetbrains template 0.8.2
- latest and greatest.

chore:upgrade to 0.8.2 jetbrains template

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
build.gradle.kts
detekt-config.yml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/services/MyProjectService.kt

plugin is based on deps from plugin template `v0.8.2`.
update plugin and its deps to match latest plugin template `v0.10.1`
latest dep versions.
Changes based of [this](https://github.com/JetBrains/intellij-platform-plugin-template/compare/v0.8.2...v0.10.1)

updated to template 0.10.1

---

.github/workflows/release.yml
CHANGELOG.md

chore: changelog update v0.9.1

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/run-ui-tests.yml
CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- updated to latest plugin template 1.1.0
- prepare for webstorm 2021.3

chore: update to latest template

---

.github/workflows/build.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties

feat: upgrade to template 1.1.2

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties

build: update gradel wrapper dep and change log updates

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/services/NodeDebugConfigState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/RunSchematicPanel.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/SchematicsListDialog.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/SchematicsListToolTab.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/NewExternalSchematicDialog.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginAppUiSettingsComponent.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsComponent.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt

feat: upgrade ui usages and refactor debug logic

---

CHANGELOG.md
gradle.properties

updated to version 0.11.0

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/run-ui-tests.yml
CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
qodana.yml
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/DryRunAction.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/actionlisteners/SchematicSelectionTabListener.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/actions/Generate.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/services/MyProjectService.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsComponent.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsConfigurable.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginProjectSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/ui/settings/PluginSettingsState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/GenerateTerminalCommand.kt

feat: support pnpm and other upgrades

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/run-ui-tests.yml
.run/Run Plugin Tests.run.xml
CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
src/main/resources/META-INF/plugin.xml

template update and version upgrade

---

.github/workflows/build.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat

build: template v1.4.0

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/main/kotlin/com/github/etkachev/nxwebstorm/services/MyProjectService.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/services/NodeDebugConfigState.kt
src/main/kotlin/com/github/etkachev/nxwebstorm/utils/ReadFile.kt

build: update to template 1.5.0
